# Site settings
title: Prefabricator
email: ali.akbar@coderespawn.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://prefabricator.io" # the base hostname & protocol for your site

twitter_username: coderespawn
github_username: coderespawn
discord_server: https://discord.gg/dRewTSU

# Build settings
markdown: kramdown
